<a href="https://colab.research.google.com/github/selinyeltekin/MyRepo/blob/master/Lab5_task03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

def jacobian_example(xyz):
  x,y,z =xyz
  return [[3*x, 2*y, z],
          [2*x, 3*y, 1],
          [1,   -1,  0]]

def function_example(xyz):
  x,y,z =xyz
  return [x**3 + y**2 + z**2, x**2 + y**3 +z, x-y]

# iterative Newton's method
def iterative_newton(fun, x_init, jacobian):
    max_iter = 50
    epsilon = 1e-8

    x_last = x_init

    for k in range(max_iter):
        # Solve J(xn)*( xn+1 - xn ) = -F(xn):
        J = np.array(jacobian(x_last))
        F = np.array(fun(x_last))

        # inverted Jacobian
        Jinv = np.linalg.inv(J)
        #  x(n+1) = x(n) − J^(−1)(x(n))*F(x(n)).
        #  np.dot - array/vector multiplication
        diff = np.dot(Jinv,F)
        x_last = x_last - diff
        
        print(x_last)        

        # Stop condition:
        if np.linalg.norm(diff) < epsilon:
            print('convergence!, nre iter:', k )
            break

    else: # only if the for loop end 'naturally'
        print('not converged')

    return x_last

x_sol = iterative_newton(function_example, [1.0,2.0,1.0], jacobian_example)
print('solution example:', x_sol )
print( function_example(x_sol) )


[-1. -1. 13.]
[-1.00000000e+00 -1.00000000e+00  1.77635684e-15]
[-1.00000000e+00 -1.00000000e+00  2.39808173e-14]
convergence!, nre iter: 2
solution example: [-1.00000000e+00 -1.00000000e+00  2.39808173e-14]
[6.661338147751514e-15, 3.064215547965436e-14, 0.0]
