<a href="https://colab.research.google.com/github/selinyeltekin/MyRepo/blob/master/Lab6_Task04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

# LU decomposition

import numpy as np

def LU_partial_decomposition(matrix):
    n, m = matrix.shape
    P = np.identity(n)
    L = np.identity(n)
    U = matrix.copy()
    PF = np.identity(n)
    LF = np.zeros((n,n))
    for k in range(0, n - 1):
        index = np.argmax(abs(U[k:,k]))
        index = index + k 

        # here we do pivoting
        if index != k:
            P = np.identity(n)
            P[[index,k],k:n] = P[[k,index],k:n]
            U[[index,k],k:n] = U[[k,index],k:n] 
            PF = np.dot(P,PF)
            LF = np.dot(P,LF)
        # and here decomposition    
        L = np.identity(n)
        for j in range(k+1,n):
            L[j,k] = -(U[j,k] / U[k,k])
            LF[j,k] = (U[j,k] / U[k,k])
        U = np.dot(L,U)
    np.fill_diagonal(LF, 1)
    return PF, LF, U

def LU_resolution(P,L,U,b):
  n, m = L.shape
  x = [0 for i in range(n)]
  y = [0 for i in range(n)]
  b_pivot = np.dot(P,b)

  for j in range(0,n):
    lx=0
    for k in range(0,j):
      lx=lx+L[j][k]*y[k]
    num = b_pivot[j]-lx
    y[j]=num/L[j][j]

  x[n-1]=y[n-1]/U[n-1][n-1]
  for j in range(n-1,-1,-1):
    ux=0
    for k in range(j+1,n):
      ux=ux+U[j][k]*x[k]
    num=y[j]-ux
    x[j]=num/U[j][j]

  return x



# Usage
A = [[1, 2, 1], [1, -2, 2], [2, 12, -2]]
A = np.array(A)
b= [0,4,4]
b= np.array(b)
P1, L1, U1 = LU_partial_decomposition(A)
x = LU_resolution(P1,L1,U1,b)


# Scipy
import scipy
import scipy.linalg
#LU decomposition using linalg.lu library function
P2, L2, U2 = scipy.linalg.lu(A) # P2 = P2.T  
#LU resolution using linalg.lu library function
x_lin=scipy.linalg.solve(A,b)

print("Input array:")
print(A)
print(" ")
print("Result. Pivoting array:")
print(P1)
print("L and U arrays:")
print(L1,"\n", U1)
print(" ")
print("Solution x")
print(x)
print(" ")
print("Result using linalg.lu function. Pivoting array:")
print(P2.T)  # transponed array
print("L and U arrays:")
print(L2,"\n", U2)
print(" ")
print("Solution x with linalg.lu.solve")
print(x_lin)

Input array:
[[ 1  2  1]
 [ 1 -2  2]
 [ 2 12 -2]]
 
Result. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
 
Solution x
[11.0, -2.5, -6.0]
 
Result using linalg.lu function. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
 
Solution x with linalg.lu.solve
[11.  -2.5 -6. ]
